name: terangapay
description: "A new Flutter project."

# Empêche la publication accidentelle sur pub.dev
publish_to: 'none'

# Version et build number
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5
  cupertino_icons: ^1.0.8
  rikulo_security: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/data/users.json

  # Exemple pour ajouter des fonts si nécessaire
#  fonts:
#    - family: Roboto
#      fonts:
#        - asset: assets/fonts/Roboto-Regular.ttf
#        - asset: assets/fonts/Roboto-Bold.ttf
#          weight: 700